"""Remove unique constraint from phone

Revision ID: 8b2d039ba672
Revises: 03a1420e0536
Create Date: 2025-03-19 15:54:25.732440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2d039ba672'
down_revision: Union[str, None] = '03a1420e0536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_phone_key', 'profile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('profile_phone_key', 'profile', ['phone'])
    # ### end Alembic commands ###
